export const icons: Record<IconName, string> = {
    instagram: '1',
    youtube: '2',
    print: '3',
    device: '4',
    cards: '5',
    notebook: '6',
    book: '7',
    chat: '8',
    quote: '9',
    question: '10',
    tasks: '11',
    email: '12',
    venmo: '13',
    call: '14',
    microphone: '15',
    web: '16',
    link: '17',
    search: '18',
    settings: '19',
    shop: '20',
    bag: '21',
    money: '22',
    cents: '23',
    behance: '24',
    creditCard: '25',
    present: '26',
    calculator: '27',
    calendar: '28',
    clock: '29',
    camera: '30',
    photo: '31',
    weather: '32',
    leaf: '33',
    other1: '34',
    dots: '35',
    recycle: '36',
    dribble: '37',
    other2: '38',
    google: '39',
    yelp: '40',
    other3: '41',
    amazon: '42',
    facebook: '43',
    ebay: '44',
    other4: '45',
    other5: '46',
    other6: '47',
    cafePress: '48',
    other7: '49',
    kickStarter: '50',
    other8: '51',
    other9: '52',
    other10: '53',
    twitter: '54',
    coffee: '55',
    other11: '56',
    other12: '57',
    other13: '58',
    mailChimp: '59',
    rss: '60',
    reddit: '61',
    discord: '62',
    webtoon: '63',
    other14: '64',
    snapchat: '65',
    medium: '66',
    blogger: '67',
    wikipedia: '68',
    wix: '69',
    weebly: '70',
    google2: '72',
    barnesAndNobles: '73',
    readLater: '74',
    other15: '75',
    tiktok: '76',
    dropbox: '77',
    googleDrive: '78',
    cloud: '79',
    other16: '80',
    other17: '81',
    skype: '82',
    other18: '83',
    video: '84',
    whatsapp: '85',
    messenger: '86',
    twitter2: '87',
    line: '88',
    soundCloud: '89',
    music: '90',
    spotify: '91',
    other: '92',
    youtube2: '93',
    googlePlay: '94',
    appleMusic: '95',
    other19: '96',
    other20: '97',
    pinterest: '98',
    other21: '99',
    other22: '100',
    xCode: '101',
    apple: '102',
    android: '103',
    playstation: '104',
    xbox: '105',
    other23: '106',
    other24: '107',
    paypal: '108',
    linkedIn: '109',
    other25: '110',
    other26: '111',
    other27: '112',
    other28: '113',
    applePay: '114',
    googlePay: '115',
    meta: '116',
    like: '117',
    love: '118',
    star: '119',
    twitch: '120',
    smiley: '121',
    other29: '122',
    user: '123',
    play: '124',
    download: '125',
    bookmark: '126',
    add: '127',
    map: '128',
    drive: '129',
    home: '130',
};

export type IconName =
    | 'instagram'
    | 'youtube'
    | 'print'
    | 'device'
    | 'cards'
    | 'notebook'
    | 'book'
    | 'chat'
    | 'quote'
    | 'question'
    | 'tasks'
    | 'email'
    | 'venmo'
    | 'call'
    | 'microphone'
    | 'web'
    | 'link'
    | 'search'
    | 'settings'
    | 'shop'
    | 'bag'
    | 'money'
    | 'cents'
    | 'behance'
    | 'creditCard'
    | 'present'
    | 'calculator'
    | 'calendar'
    | 'clock'
    | 'camera'
    | 'photo'
    | 'weather'
    | 'leaf'
    | 'other1'
    | 'dots'
    | 'recycle'
    | 'dribble'
    | 'other2'
    | 'google'
    | 'yelp'
    | 'other3'
    | 'amazon'
    | 'facebook'
    | 'ebay'
    | 'other4'
    | 'other5'
    | 'other6'
    | 'cafePress'
    | 'other7'
    | 'kickStarter'
    | 'other8'
    | 'other9'
    | 'other10'
    | 'twitter'
    | 'coffee'
    | 'other11'
    | 'other12'
    | 'other13'
    | 'mailChimp'
    | 'rss'
    | 'reddit'
    | 'discord'
    | 'webtoon'
    | 'other14'
    | 'snapchat'
    | 'medium'
    | 'blogger'
    | 'wikipedia'
    | 'wix'
    | 'weebly'
    | 'other14'
    | 'google2'
    | 'barnesAndNobles'
    | 'readLater'
    | 'other15'
    | 'tiktok'
    | 'dropbox'
    | 'googleDrive'
    | 'cloud'
    | 'other16'
    | 'other17'
    | 'skype'
    | 'other18'
    | 'video'
    | 'whatsapp'
    | 'messenger'
    | 'twitter2'
    | 'line'
    | 'soundCloud'
    | 'music'
    | 'spotify'
    | 'other'
    | 'youtube2'
    | 'googlePlay'
    | 'appleMusic'
    | 'other19'
    | 'other20'
    | 'pinterest'
    | 'other21'
    | 'other22'
    | 'xCode'
    | 'apple'
    | 'android'
    | 'playstation'
    | 'xbox'
    | 'other23'
    | 'other24'
    | 'paypal'
    | 'linkedIn'
    | 'other25'
    | 'other26'
    | 'other27'
    | 'other28'
    | 'applePay'
    | 'googlePay'
    | 'meta'
    | 'like'
    | 'love'
    | 'star'
    | 'twitch'
    | 'smiley'
    | 'other29'
    | 'user'
    | 'play'
    | 'download'
    | 'bookmark'
    | 'add'
    | 'map'
    | 'drive'
    | 'home';
